# Generated by Django 4.2.11 on 2024-03-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_sqluser',
        ),
        migrations.AddField(
            model_name='user',
            name='is_sqluser_change',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the SQL explorer app with permissions to view/add/change/delete/execute queries.', verbose_name='SQL explorer user status (view/add/change/delete/execute)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sqluser_view',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the SQL explorer app with permissions to only view and execute existing queries.', verbose_name='SQL explorer user status (view/execute existing queries only)'),
        ),
    ]
