# Generated by Django 4.1 on 2023-05-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioSampleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(max_length=128)),
                ('sample_processing', models.CharField(max_length=128)),
                ('freezing_time', models.IntegerField(default=0)),
                ('thawing_time', models.IntegerField(default=0)),
                ('spectra_measurment', models.CharField(max_length=128)),
                ('spectrometer', models.CharField(max_length=128)),
                ('atr_crystal', models.CharField(max_length=128)),
                ('acquisition_time', models.IntegerField(default=0)),
                ('n_coadditions', models.IntegerField(default=0)),
                ('resolution', models.IntegerField(default=0)),
                ('wavelengths', models.IntegerField(default=0)),
                ('intensities', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMetaData',
            fields=[
                ('patient_id', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('days_of_symptoms', models.IntegerField(default=0)),
                ('fever', models.BooleanField(default=False)),
                ('dyspnoea', models.BooleanField(default=False)),
                ('oxygen_saturation_lt_95', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('coryza', models.BooleanField(default=False)),
                ('odinophagy', models.BooleanField(default=False)),
                ('diarrhea', models.BooleanField(default=False)),
                ('nausea', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('weakness', models.BooleanField(default=False)),
                ('anosmia', models.BooleanField(default=False)),
                ('myalgia', models.BooleanField(default=False)),
                ('no_appetite', models.BooleanField(default=False)),
                ('vomiting', models.BooleanField(default=False)),
                ('suspicious_contact', models.BooleanField(default=False)),
                ('chronic_pulmonary_inc_asthma', models.BooleanField(default=False)),
                ('cardiovascular_disease_inc_hypertension', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('chronic_or_neuromuscular_neurological_disease', models.BooleanField(default=False)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.biosampledata')),
            ],
        ),
    ]
