# Generated by Django 4.1 on 2023-05-11 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BioSampleData',
            new_name='BioSample',
        ),
        migrations.RenameModel(
            old_name='PatientMetaData',
            new_name='Patient',
        ),
    ]
