# Generated by Django 4.2.3 on 2023-07-25 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="symptom",
            name="disease",
        ),
        migrations.RemoveField(
            model_name="symptom",
            name="visit",
        ),
        migrations.CreateModel(
            name="DataInputForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom",
                        to="uploader.disease",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom",
                        to="uploader.symptom",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom",
                        to="uploader.visit",
                    ),
                ),
            ],
        ),
    ]
