# Generated by Django 4.2.1 on 2023-06-23 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_visit_previous_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='previous_visit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_visit', to='uploader.visit'),
        ),
    ]
