# Generated by Django 4.2.11 on 2024-04-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_biosample_freezing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='thawing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Thawing time (minutes)'),
        ),
    ]
