# Generated by Django 4.2.1 on 2023-06-23 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_visit_previous_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='value_class',
            field=models.CharField(blank=True, choices=[('BOOL', 'Bool'), ('STR', 'Str'), ('INT', 'Int'), ('FLOAT', 'Float')], default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
