# Generated by Django 4.2.11 on 2024-05-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_alter_biosample_thawing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='centrifuge_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Extraction Tube Centrifuge Time [s]'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='freezing_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Freezing Temperature [C]'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='freezing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Freezing time [days]'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='thawing_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Thawing Temperature [C]'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='thawing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Thawing time [minutes]'),
        ),
        migrations.AlterField(
            model_name='spectraldata',
            name='resolution',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resolution [1/cm]'),
        ),
    ]
