# Generated by Django 4.2.1 on 2023-06-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_alter_disease_value_class_alter_visit_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='value_class',
            field=models.CharField(blank=True, choices=[('BOOL', 'Bool'), ('STR', 'Str'), ('INT', 'Int'), ('FLOAT', 'Float')], default='', max_length=128, null=True),
        ),
    ]
