# Generated by Django 4.2.11 on 2024-04-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_cid',
            field=models.UUIDField(blank=True, help_text='Patient ID prescribed by the associated center', null=True),
        ),
    ]
