# Generated by Django 4.2.11 on 2024-04-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_patient_patient_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biosample',
            name='freezing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Freezing time (days)'),
        ),
        migrations.AlterField(
            model_name='biosample',
            name='thawing_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thawing time (minutes)'),
        ),
    ]
