# Generated by Django 4.2.11 on 2024-03-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_is_sqluser_user_is_sqluser_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='user.center'),
        ),
    ]
